pages:
  image: python:3.10
  script:
    - apt-get update && apt-get install -y doxygen
    - pip install sphinx sphinx-rtd-theme breathe
    - cd docs
    - doxygen Doxyfile # Generates C++ XML
    - make html        # Sphinx builds the final site
    - mv _build/html/ ../public
  artifacts:
    paths:
      - public
  only:
    - main
