common_base_frame: mount_link

left:
  arm_side: left
  linear_multiplier: 0.9
  angular_multiplier: 0.9
  kp_linear: 20.0
  kp_angular: 20.0
  collision_distance: 0.35
  controller_to_robot_rotation: [0.440, 0.174, -0.881, -0.500, -0.767, -0.401, -0.746, 0.617, -0.251]

right:
  arm_side: right
  linear_multiplier: 0.9
  angular_multiplier: 0.9
  kp_linear: 8.0
  kp_angular: 8.0
  collision_distance: 0.20
  controller_to_robot_rotation: [-0.440, 0.174, -0.881, -0.500, 0.767, 0.401, 0.746, 0.617, -0.251]
