left:
  hand_side: left
  base_frame: base
  ee_frame: left_fr3v2_hand_tcp
  other_ee_frame: right_fr3v2_hand_tcp
  pose_topic: /oculus/left_controller_pose
  button_topic: /oculus/left_controller_buttons
  twist_topic: /left/servo_node/delta_twist_cmds
  gripper_action: /left_hand_controller/gripper_cmd
  servo_start_service: /left/servo_node/start_servo
  linear_multiplier: 0.9
  angular_multiplier: 0.0
  kp_linear: 8.0
  kp_angular: 8.0
  collision_distance: 0.20
  controller_forward_axis: "z"
  controller_left_axis: "x"
  controller_up_axis: "y"
  controller_forward_sign: -1.0
  controller_left_sign: -1.0
  controller_up_sign: 1.0
  controller_roll_sign: 1.0
  controller_pitch_sign: 1.0
  controller_yaw_sign: -1.0

right:
  hand_side: right
  base_frame: base
  ee_frame: right_fr3v2_hand_tcp
  other_ee_frame: left_fr3v2_hand_tcp
  pose_topic: /oculus/right_controller_pose
  button_topic: /oculus/right_controller_buttons
  twist_topic: /right/servo_node/delta_twist_cmds
  gripper_action: /right_hand_controller/gripper_cmd
  servo_start_service: /right/servo_node/start_servo
  linear_multiplier: 0.9
  angular_multiplier: 0.0
  kp_linear: 8.0
  kp_angular: 8.0
  collision_distance: 0.20
  controller_forward_axis: "z"
  controller_left_axis: "x"
  controller_up_axis: "y"
  controller_forward_sign: -1.0
  controller_left_sign: -1.0
  controller_up_sign: 1.0
  controller_roll_sign: 1.0
  controller_pitch_sign: 1.0
  controller_yaw_sign: -1.0
